name: new_lab
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  path: ^1.7.0
  http: ^0.13.4
  mysql1: ^0.19.2
  intl: ^0.17.0
  pdf: ^3.6.5
  xml: ^5.3.1
  test: ^1.18.1

dev_dependencies:
  
  lints: ^1.0.0
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
